export const homepageTemplateBlockSchema = {
  name: 'homepageTemplate',
  label: 'Homepage Template Content',
  fields: [
        {
          type: 'object',
          name: 'hero',
          label: 'Hero Section',
          fields: [
            { name: 'eyebrow', label: 'Eyebrow', type: 'string' },
            { name: 'title', label: 'Headline', type: 'string' },
            { name: 'description', label: 'Description', type: 'string', ui: { component: 'textarea' } },
            { name: 'buttonText', label: 'Featured Story Label', type: 'string', description: 'Text label shown beside the hero eyebrow. This is not a button and does not link anywhere.' },
            { name: 'buttonLink', label: 'Unused Legacy Link', type: 'string', description: 'Kept only for TinaCloud schema compatibility. The Featured Story label does not use this link.' },
            { name: 'image', label: 'Hero Image', type: 'image' },
            { name: 'imageAlt', label: 'Hero Image Alt Text', type: 'string' },
          ],
        },
        {
          type: 'object',
          name: 'why',
          label: 'About / Editorial Standards Section',
          fields: [
            { name: 'eyebrow', label: 'Eyebrow', type: 'string' },
            { name: 'title', label: 'Heading', type: 'string' },
            { name: 'paragraphOne', label: 'Paragraph 1', type: 'string', ui: { component: 'textarea' } },
            { name: 'paragraphTwo', label: 'Paragraph 2', type: 'string', ui: { component: 'textarea' } },
            { name: 'ctaText', label: 'About CTA Text', type: 'string' },
            { name: 'ctaLink', label: 'About CTA Link', type: 'string' },
            { name: 'standardsEyebrow', label: 'Editorial Standards Eyebrow', type: 'string' },
            { name: 'standardsTitle', label: 'Editorial Standards Heading', type: 'string' },
            {
              type: 'object',
              list: true,
              name: 'standards',
              label: 'Standards Cards',
              fields: [
                { name: 'label', label: 'Standard Number', type: 'string' },
                { name: 'title', label: 'Standard Title', type: 'string' },
                { name: 'text', label: 'Standard Definition', type: 'string', ui: { component: 'textarea' } },
                { name: 'practiceLabel', label: 'Practice Label', type: 'string' },
                { name: 'practiceText', label: 'Practice Text', type: 'string', ui: { component: 'textarea' } },
              ],
            },
          ],
        },
        {
          type: 'object',
          name: 'newsroom',
          label: 'More Reporting Section',
          fields: [
            { name: 'heading', label: 'More Reporting Heading', type: 'string' },
            { name: 'subheading', label: 'More Reporting Eyebrow', type: 'string' },
            { name: 'submitHeading', label: 'Legacy Submit Panel Heading', type: 'string' },
            { name: 'submitButtonText', label: 'Submit Button Text', type: 'string' },
            { name: 'submitButtonLink', label: 'Submit Button Link', type: 'string' },
            {
              type: 'object',
              list: true,
              name: 'prompts',
              label: 'Submit Prompt Items',
              fields: [
                { name: 'title', label: 'Title', type: 'string' },
                { name: 'text', label: 'Text', type: 'string', ui: { component: 'textarea' } },
              ],
            },
          ],
        },
        {
          type: 'object',
          name: 'wireFeature',
          label: 'Editorial Standards Note Card',
          fields: [
            { name: 'eyebrow', label: 'Eyebrow', type: 'string' },
            { name: 'quote', label: 'Quote', type: 'string', ui: { component: 'textarea' } },
            { name: 'author', label: 'Author Name', type: 'string' },
            { name: 'byline', label: 'Note Text', type: 'string' },
            { name: 'buttonText', label: 'Note CTA Text', type: 'string' },
            { name: 'buttonLink', label: 'Note CTA Link', type: 'string' },
            { name: 'image', label: 'Feature Image', type: 'image' },
            { name: 'imageAlt', label: 'Feature Image Alt Text', type: 'string' },
          ],
        },
        {
          type: 'object',
          name: 'coverage',
          label: 'What We Cover Section',
          fields: [
            { name: 'title', label: 'Heading', type: 'string' },
            { name: 'description', label: 'Description', type: 'string', ui: { component: 'textarea' } },
            {
              type: 'object',
              list: true,
              name: 'topics',
              label: 'Coverage Topic Cards',
              fields: [
                { name: 'number', label: 'Number', type: 'string' },
                { name: 'title', label: 'Topic Title', type: 'string' },
                { name: 'text', label: 'Topic Text', type: 'string', ui: { component: 'textarea' } },
              ],
            },
          ],
        },
        {
          type: 'object',
          name: 'contact',
          label: 'Our Team Section',
          fields: [
            { name: 'eyebrow', label: 'Eyebrow', type: 'string' },
            { name: 'title', label: 'Heading', type: 'string' },
            { name: 'description', label: 'Description', type: 'string', ui: { component: 'textarea' } },
            { name: 'note', label: 'Section Note', type: 'string', ui: { component: 'textarea' } },
            { name: 'leadLabel', label: 'Lead Team Member Label', type: 'string' },
            {
              type: 'object',
              list: true,
              name: 'cards',
              label: 'Team Member Cards',
              fields: [
                { name: 'title', label: 'Team Member Name', type: 'string' },
                { name: 'email', label: 'Role / Location', type: 'string' },
                { name: 'image', label: 'Team Member Image', type: 'image' },
                { name: 'imageAlt', label: 'Team Member Image Alt Text', type: 'string' },
                { name: 'text', label: 'Bio / Card Text', type: 'string', ui: { component: 'textarea' } },
                { name: 'accent', label: 'Lead Team Member', type: 'boolean' },
              ],
            },
          ],
        },
      ],
};
